name: Latest blog post workflow

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull in Velog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://api.velog.io/rss/@jun0321"
          max_post_count: 5
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          committer_username: github-actions[bot]
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
